name: Job Watcher Bot

on:
  schedule:
    - cron: '*/5 * * * *' # Request to run every 5 mins
  workflow_dispatch:      # Allows manual testing

permissions:
  contents: write

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 10   # Safety limit

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Job Scraper
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Commit Memory File
        run: |
          git config --global user.name "JobBot"
          git config --global user.email "bot@noreply.github.com"
          git add seen_jobs.json
          # Only commit if the file actually changed
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update seen jobs" && git push)
